AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - lib/templates/rails/scaffold_controller/*
    - lib/templates/rails/helper/*
    - lib/templates/active_record/model/*
    - app/channels
    - node_modules/**/*
    - bin/webpack
    - bin/webpack-dev-server
Metrics/LineLength:
  Max: 160
Style/BlockComments:
  Description: 'Do not use block comments.'
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - spec/support/omniauth.rb
Metrics/AbcSize:
  Exclude:
    - spec/support/omniauth.rb
