default: &default
  adapter: postgresql
  encoding: utf8
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username:

development:
  <<: *default
  database: skeleton_development

test: &test
  <<: *default
  database: skeleton_test

cucumber:
  <<: *test

production:
  <<: *default
  database: <%= ENV['SKELETON_DATABASE_NAME'] %>
  username: <%= ENV['SKELETON_DATABASE_USERNAME'] %>
  password: <%= ENV['SKELETON_DATABASE_PASSWORD'] %>
